//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sesi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public string id { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public string type_id { get; set; }
    
        public virtual item_types item_types { get; set; }
    }
}
