//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LatihanKuis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDo
    {
        public string TodoId { get; set; }
        public string Name { get; set; }
        public int Reward { get; set; }
        public string Category { get; set; }
        public string UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
