//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sesi4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string id { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public int stock { get; set; }
        public string type_id { get; set; }
    
        public virtual Item_Type Item_Type { get; set; }
    }
}
